server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
      routes:
        - id: first
          uri: lb://first-service
          predicates:
            - Path=/first/**
        - id: second
          uri: lb://second-service
          predicates:
            - Path=/second/**